WIP: added i18n using Spanish as example
performant-software/neatline-spa pull request #63
Opened 2018-07-17 19:33 UTC by mkobayashi21

build, taking away all buttons to change language except in homepage
first steps/WIP to #42

2018-07-17 20:24 UTC, akstuhl requested changes
Hi @mkobayashi21, excellent work on this. The language toggling works seamlessly and the syntax is very straightforward. react-localization seems like a good fit for this project based on your implementation. One change needs to be made before you merge: in some of the components, there are lines setting/getting the `strings` variable in the react `state` object. This appears to be unnecessary based on my testing (`strings` is already available to the component via your import statement), and will generate a console error because react tries to prevent you from modifying the `state` object directly. I think I flagged all the lines that should be removed with inline comments here. If you can try removing those and confirm everything still displays correctly, this will be in great shape. Thanks!

2018-07-17 20:24 UTC, akstuhl commented on src/components/RecordForm/index.js
> +		const strings = this.state.strings;
This line should be unneeded.

2018-07-17 20:24 UTC, akstuhl commented on src/components/exhibitForm.js
> +		this.state = {strings};
Unneeded (see review summary comment)

2018-07-17 20:24 UTC, akstuhl commented on src/components/exhibitForm.js
> +		const strings = this.state.strings;
Unneeded (see review summary comment)

2018-07-17 20:24 UTC, akstuhl commented on src/views/exhibits/index.js
> +    this.state = {strings};
Unneeded (see review summary comment)

2018-07-17 20:24 UTC, akstuhl commented on src/views/exhibits/index.js
> +    const strings = this.state.strings;
Unneeded (see review summary comment)

2018-07-17 20:24 UTC, akstuhl commented on src/views/exhibits/show.js
> +		this.state = {strings};
Unneeded (see review summary comment)

2018-07-17 20:24 UTC, akstuhl commented on src/views/exhibits/show.js
> +		const strings = this.state.strings;
Unneeded (see review summary comment)

2018-07-18 14:23 UTC, mkobayashi21 commented
Should be fine now; thank you @akstuhl  for reviewing!

2018-07-18 14:50 UTC, akstuhl approved these changes

2018-07-18 14:56 UTC, jamiefolsom approved these changes
Looks good to me 👍 🎉

2018-07-18 14:56 UTC, jamiefolsom commented on src/i18nLibrary.js
> +   //to demonstrate the i18n functionality, with no intent to offend anyone.
Love it

2018-07-18 14:56 UTC, jamiefolsom commented on src/i18nLibrary.js
> +export let strings = new LocalizedStrings({
Is there an easy way to export (or factor out) the strings as a text file, to be worked on by translators, then re-imported, pre-build?

2018-07-18 14:56 UTC, jamiefolsom commented on src/views/exhibits/index.js
> +        <button onClick={() => changeLanguage("en")}>en</button>
Idea for discussion: could we detect available languages, and add buttons for each?

2018-07-18 14:58 UTC, jamiefolsom commented
@mkobayashi21 if you would, rebase against master, and squash all but the first commit; if we can keep this PR open, and rebased on master for now, we might wait for @ZoeLeBlanc to review it.

2018-07-18 15:09 UTC, mkobayashi21 commented
Thanks @jamiefolsom ! It should be rebased/squashed now, and I will look into the questions that you raised.

2018-07-18 17:50 UTC, jamiefolsom commented
Trying to reopen.

2018-07-26 19:31 UTC, merged